@startuml



start
fork
    repeat
        :Produce new data;
        :Add data to queue;
        :Enter low-power mode until\nmeasurement period elapsed;
        note left: If single-core,\nsimply idle this\nprocess instead
    repeat while ()

fork again
    repeat
        partition "Receive Mode" {
            :Calculate the next pass with\nwhich to attempt transmission;
            note left: This step itself is quite\ncomplex and deserves\nits own diagram
        }
        
        partition "Sleep Mode" {
            :Put modem to sleep until\n15 minutes before midpoint\nof selected pass;
            :Enter low-power mode until\n15 minutes before midpoint\nof selected pass;
            note left: If single-core,\nsimply idle this\nprocess instead
        }

        partition "GPS Acquisition Mode" {
            :Wait for GPS fix;
        }

        partition "Receive Mode" {
            if (RF background noise <= -93 dBm?) then (yes)
                repeat
                    :Bundle data from queue;
                    :Transmit bundled data;
                repeat while (More data in queue?) is (yes)
                repeat
                    if (Packets in transmit queue?) then (no)
                        break
                    else (yes)
                        
                    endif
                repeat while (Pass is complete?) is (no)
            else (no)
            endif
        }
        floating note: May or may not\nintermittently enter\nTransmit Mode

    repeat while ()

end fork

@enduml