@startuml
:Define High-Level Requirements;
:Evaluate Transmission Protocols and Schemes;
:Define Satellite IoT Requirements;
:Design and Implement First Prototype;
:Design and Implement Second Prototype;
:Design and Simulate Satellite\nPass Selection Algorithm;
:Construct Energy Model of Satellite IoT Modem;
@enduml
